# Generated by Django 2.1.7 on 2019-05-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=20)),
                ('store_number', models.SmallIntegerField()),
                ('jsocver', models.CharField(max_length=10)),
                ('RHEL_version', models.SmallIntegerField(max_length=5)),
                ('bridge_count', models.SmallIntegerField(max_length=5)),
                ('progressrjbridge_GB', models.CharField(max_length=10)),
                ('retailjstaticdata_UK', models.CharField(max_length=10)),
                ('commonutilities_GB', models.CharField(max_length=10)),
                ('callcentreinstore_GB', models.CharField(max_length=10)),
                ('storeserver_GB', models.CharField(max_length=10)),
                ('storeprogresscode_GB', models.CharField(max_length=10)),
                ('socrates_GB', models.CharField(max_length=10)),
                ('rjsoabridge_GB', models.CharField(max_length=10)),
                ('socratesContainer', models.CharField(max_length=10)),
                ('socratesBroker', models.CharField(max_length=10)),
                ('ccApp', models.CharField(max_length=10)),
                ('sgmb', models.CharField(max_length=10)),
                ('mysqld', models.CharField(max_length=10)),
                ('backoffice', models.CharField(max_length=10)),
                ('httpd', models.CharField(max_length=10)),
                ('progress_to_rj_bridge', models.CharField(max_length=10)),
                ('rj_to_soa_bridge', models.CharField(max_length=10)),
                ('Deployment_type', models.CharField(max_length=10)),
                ('Store_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
