# Generated by Django 2.1.7 on 2019-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pilot', '0002_auto_20190509_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='RHEL_version',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='bridge_count',
            field=models.SmallIntegerField(),
        ),
    ]
